version: 2.1

jobs:
  identity:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: 
          command: |
            echo "Hello, this is job: ${CIRCLE_WORKFLOW_ID_JOB_ID}"
            echo "And, I was triggered via << pipeline.trigger_source >>"

parameters:
  run_specs_on_main_branch:
    type: boolean
    default: false

workflows:
  main:
    when:
      or:
        - and:
            - equal: [ main, << pipeline.git.branch >> ]
            - << pipeline.parameters.run_specs_on_main_branch >>
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - identity    
