version: 2.1

jobs:
  identity:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: 
          command: |
            echo "Hello, this is job: ${CIRCLE_WORKFLOW_ID_JOB_ID}"
            echo "And, I was triggered via << pipeline.trigger_source >>"

workflows:
  main:
    when:
      equal: [ 'webhook', << pipeline.trigger_source >> ]
    jobs:
      - identity
  every_10m:
    when:
      equal: [ 'scheduled', << pipeline.trigger_source >> ]
    jobs:
      - identity
    triggers:
      - schedule:
          # every 10 minutes!
          cron: '*/10 * * * *'
