version: 2.1

jobs:
  noop:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo done
  identity:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: 
          command: |
            echo "Hello, this is job: ${CIRCLE_WORKFLOW_ID_JOB_ID}"
            echo "And, I was triggered via << pipeline.trigger_source >>"

parameters:
  run_specs_on_main_branch:
    type: boolean
    default: false

workflows:
  main:
    when: true
    jobs:
      - identity:
          filters:
            branches:
              only:
                - /^feature.*/
                - /^bugfix.*/
                - /^other.*/
                - /^hotfix.*/
                - /^release.*/
                - /^revert-.*/
      - noop:
          requires:
            - identity
